spring:
  application:
    name: app
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
        group-id: restaurant-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto-offset-reset: earliest
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_RESTAURANT_DB}
    username: ${MYSQL_RESTAURANT_USER}
    password: ${MYSQL_RESTAURANT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
        host: localhost
        port: 6379
        password: ${REDIS_RESTAURANT_PASS}

app:
  internal-api-key: ${RESTAURANT_INTERNAL_API_KEY}

api:
  security:
    jwt:
      secret: ${TOKEN_SECRET}

springdoc:
  swagger-ui:
    path: /api/docs
  api-docs:
    path: /api/docs/v3